//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.ExamQuestions = new HashSet<ExamQuestion>();
            this.Results = new HashSet<Result>();
        }
    
        public long ExamID { get; set; }
        public int GroupID { get; set; }
        public long CandidateID { get; set; }
        public Nullable<long> ExamDuration { get; set; }
        public string ExamStatus { get; set; }
        public Nullable<System.DateTime> ConductedOn { get; set; }
        public Nullable<System.DateTime> LastActiveSession { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<decimal> ObtainedMarks { get; set; }
        public string ExamResult { get; set; }
        public string Commment { get; set; }
        public Nullable<System.DateTime> ScheduledOn { get; set; }
        public Nullable<long> ScheduledBy { get; set; }
        public Nullable<long> ReScheduledBy { get; set; }
        public Nullable<System.DateTime> ReScheduledOn { get; set; }
        public Nullable<long> ConductedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ExamUser ExamUser { get; set; }
        public virtual GroupMaster GroupMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
    }
}
