//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizMaster()
        {
            this.ExamQuestions = new HashSet<ExamQuestion>();
            this.OptionMasters = new HashSet<OptionMaster>();
        }
    
        public long QuestionID { get; set; }
        public int SubGroupID { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public string QuestionType { get; set; }
        public string Question { get; set; }
        public int MaxMarks { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionMaster> OptionMasters { get; set; }
        public virtual SubGroupMaster SubGroupMaster { get; set; }
    }
}
